config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index"
    resources :pages
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  with_options only: [:index, :show] do |for_users|
    for_users.resources :pages
    for_users.resources :products
  end

  resources :orders
  resources :product_orders

end

app/views/admin/pages/_form.html.erb
<%= simple_form_for([:admin, @page], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :title, label: "Título", input_html: { class: "form-control" } %>
  <%= f.input :body, label: "Texto", input_html: { class: "form-control ckeditor" } %> <br/>
  <%= f.button :submit, "Salvar", class: "btn btn-success btn-sm" %>
  <%= link_to "Cancelar", admin_pages_path, class: "text-danger" %>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editando página</div>
  <div class="panel-body">
    <div class="col-md-12" data-no-turbolink>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/pages/index.html.erb
<div class="panel panel-default" ng-controller="indexPageCtrl">
  <div class="panel-heading"><strong>Páginas</strong> | <%= link_to "Nova página", new_admin_page_path, class: "btn btn-xs btn-success" %></div>
  <div class="panel-heading">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Filtro" ng-model="search">
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Título</th>
        <th>Data de criação</th>
        <th width="30"></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="page in pages | filter: search" ng-cloak>
        <td>{{page.id}}</td>
        <td>{{page.title}}</td>
        <td>{{page.created_at | date: 'dd/MM/yyyy'}}</td>
        <td ng-click="edit(page.id)"><button class="btn btn-primary btn-xs">Editar</button></td>
        <td ng-click="remove(page.id, $index)"><button class="btn btn-danger btn-xs">Delete</button></td>
      </tr>
    </tbody>
  </table>
</div>
<p><%= link_to "Nova página", new_admin_page_path, class: "btn btn-sm btn-success" %></p>

app/views/admin/pages/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Nova página</div>
  <div class="panel-body">
    <div class="col-md-12" data-no-turbolink>
      <%= render 'form' %>
    </div>
  </div>
</div>