config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index"
    resources :pages
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  with_options only: [:index, :show] do |for_users|
    for_users.resources :pages
    for_users.resources :products
  end

  resources :orders
  resources :product_orders

end

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_filter :set_product_order, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @product_orders = ProductOrder.where(user_id: current_user.id)
  end

  def show
  end

  def edit
  end

  def new
    @product_order = ProductOrder.new
  end

  def create
    @product_order = ProductOrder.new(product_order_params)
    respond_to do |format|
      @product_order.user_id = current_user.id
      if @product_order.save
        format.html { redirect_to product_orders_path, notice: 'Produto adicionado com sucesso.' }
      else
        format.html { redirect_to product_path(@product_order.product_id), notice: 'Não possível adicionar o produto.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @product_order.update(product_order_params)
        format.html { redirect_to orders_path, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product_order.destroy
        format.html { redirect_to product_orders_path, notice: 'Produto removido com sucesso.' }
        format.json { render :show, status: :ok }
      else
        format.html { redirect_to orders_path }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_product_order
    @product_order ||= ProductOrder.find(params[:id])
  end

  def product_order_params
    params.require(:product_order).permit(
      :product_id, :product_name, :product_description, :product_price,
      :product_quantity, :user_id, :order_id
    )
  end
end

app/views/product_orders/index.html.erb
<table class="table">
  <thead>
    <tr>
      <td>Título</td>
      <td>Quantidade</td>
      <td>Valor Unit.</td>
      <td>Total</td>
      <td>Adicionado em</td>
      <td width="30"></td>
    </tr>
  </thead>
  <tbody>
    <% @product_orders.each do |porder| %>
      <tr>
        <td><%= porder.product_name %></td>
        <td><%= porder.product_quantity %></td>
        <td><%= porder.product_price %></td>
        <td><%= porder.product_price * porder.product_quantity %></td>
        <td><%= porder.created_at %></td>
        <td><%= link_to "Remover", product_order_path(porder), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Deseja realmente remover este produto?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Fazer pedido", new_order_path, class: 'btn btn-lg btn-success' %>