config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index"
    resources :pages
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  with_options only: [:index, :show] do |for_users|
    for_users.resources :pages
    for_users.resources :products
  end

  resources :orders
  resources :product_orders

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ProductUploader
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    # before_action :check_permission, except: [:new, :edit, :create, :update, :destroy]

    def index
      if current_user.role == "Administrador"
        @products = Product.all
      else
        @products = Product.where(user_id: current_user.id)
      end
    end

    def show
    end

    def new
      @product = Product.new
    end

    def edit
    end

    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_path, notice: "Produto criado com sucesso." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_path, notice: 'Produto atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy

    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :code, :slug, :image,
                                      :price, :sold, :quantity, :featured, :user_id, :category_id)
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :set_product, only: [:show]

  def index
    @products = Product.where(sold: [false, nil]).order("RAND()").first(12)
  end

  def show
  end

  private

  def set_product
    @product ||= Product.find(params[:id])
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.input :name, label: "Nome", input_html: { class: "form-control" } %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :price, label: "Preço", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-4">
      <%= f.input :quantity, label: "Quantidade", input_html: { class: "form-control" } %>
    </div>
    <div class="col-md-4">
      <%= f.association :category, label: "Categoria" %>
    </div>
    <% if current_user.role == "Administrador" %>
    <div class="col-md-4">
      <%= f.association :user, label: "Anunciante" %>
    </div>
    <% else %>
      <%= f.input :user, as: :hidden, input_html: { value: current_user.id } %>
    <% end %>
    <div class="col-md-4">
      <%= f.input :image, label: "Imagem" %>
    </div>
    <div class="col-md-2">
      <%= f.input :sold, label: "Vendido" %>
    </div>
  </div>
  <%= f.input :description, label: "Descrição", input_html: { class: "form-control ckeditor" } %>
  <br/>
  <%= f.button :submit, "Salvar", class: "btn btn-success btn-sm" %>
  <%= link_to "Cancelar", admin_products_path, class: "text-danger" %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editando produto</div>
  <div class="panel-body">
    <div class="col-md-12" data-no-turbolink>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="panel panel-default" ng-controller="indexAdminProductCtrl">
  <div class="panel-heading"><strong>Produtos</strong> | <%= link_to "Novo produto", new_admin_product_path, class: "btn btn-xs btn-success" %></div>
  <div class="panel-heading">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Filtro">
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Quantidade</th>
        <th>Preço</th>
        <th>Anunciante</th>
        <th>Data de criação</th>
        <th width="30"></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="product in products | filter: search" ng-cloak>
        <td>{{product.id}}</td>
        <td>{{product.name}}</td>
        <td>{{product.quantity}}</td>
        <td>{{product.price}}</td>
        <td>{{product.user}}</td>
        <td>{{product.created_at | date: 'dd/MM/yyyy'}}</td>
        <td ng-click="edit(product.id)"><button class="btn btn-primary btn-xs">Editar</button></td>
        <td ng-click="remove(product.id, $index)"><button class="btn btn-danger btn-xs">Delete</button></td>
      </tr>
    </tbody>
  </table>
</div>
<p><%= link_to "Novo produto", new_admin_product_path, class: "btn btn-sm btn-success" %></p>

app/views/admin/products/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Novo produto</div>
  <div class="panel-body">
    <div class="col-md-12" data-no-turbolink>
      <%= render 'form' %>
    </div>
  </div>
</div>