config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index"
    resources :pages
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  with_options only: [:index, :show] do |for_users|
    for_users.resources :pages
    for_users.resources :products
  end

  resources :orders
  resources :product_orders

end

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Sebbo (admin)</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Páginas", admin_pages_path %></li>
        <li><%= link_to "Usuários", admin_users_path %></li>
        <li><%= link_to "Produtos", admin_products_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Ir p/ o site", root_path %></li>
        <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sebbo", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default" ng-model="search">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><% if current_user.name == nil %><%= current_user.email %><% else %><%=current_user.name %><% end %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Carrinho de compra", product_orders_path %></li>
              <li><%= link_to "Acessar painel", admin_root_path %></li>
              <li><%= link_to "Editar perfil", edit_admin_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Entrar", new_user_session_path %></li>
          <li><%= link_to "Cadastrar", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html ng-app="adminModule">
<head>
  <title>Sebbo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= render 'layouts/admin_navigation' %>
<% end %>
<div class="container">
  <div class="col-md-12">
    <% if flash[:notice] -%>
      <div class="alert alert-info" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="clientModule" ng-cloak>
<head>
  <title>Sebbo</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<div class="container">
  <div class="col-md-12">
    <% if flash[:notice] -%>
      <div class="alert alert-info" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<%= javascript_include_tag 'application' %>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'sebboecommerce';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
</body>
</html>